import React, { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Heart, Layers } from "lucide-react";
import { useLibrary } from "../../hooks/useLibrary";
import type { Comic } from "../../types/comic";
import { CoverFlow } from "../../components/library/CoverFlow";
import { ComicCard } from "../../components/library/ComicCard";
import { ComicDetailModal } from "../../components/library/ComicDetailModal";
import { ProgressUpdateModal } from "../../components/library/ProgressUpdateModal";
import { supabase } from "../../services/supabaseClient";
import { getAssetUrls } from "../../services/assetUrls";

const slug = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
const publisherArt = (name: string) => /dc comics|^dc$/i.test(name) ? "/publisher-art/dc.png" : /marvel/i.test(name) ? "/publisher-art/marvel.png" : /jbc/i.test(name) ? "/publisher-art/jbc.png" : /new.?pop/i.test(name) ? "/publisher-art/newpop.png" : undefined;
const sagaArt = (name: string) => { const value = slug(name); return value.includes("batman") ? "/saga-art/batman.png" : value.includes("superman") ? "/saga-art/superman.png" : value.includes("x-men") ? "/saga-art/x-men.png" : value.includes("lanterna verde") || value.includes("green lantern") ? "/saga-art/green-lantern.png" : undefined; };

export const SeriesPage: React.FC<{ onOpenReader: (id: string) => void }> = ({ onOpenReader }) => {
  const { allComics, seriesList, favoriteSeriesIds, toggleFavorite, toggleSeriesFavorite, updateProgress, setStatus, isLoading } = useLibrary();
  const [publisher, setPublisher] = useState<string | null>(null);
  const [seriesId, setSeriesId] = useState<string | null>(null);
  const [kind, setKind] = useState<"all" | "collection" | "saga">("all");
  const [groupSearch, setGroupSearch] = useState("");
  const [issueSearch, setIssueSearch] = useState("");
  const [issueStatus, setIssueStatus] = useState("all");
  const [issueSort, setIssueSort] = useState("issue");
  const [activePublisher, setActivePublisher] = useState(0);
  const [activeSeries, setActiveSeries] = useState(0);
  const [activeSaga, setActiveSaga] = useState(0);
  const [assetUrls, setAssetUrls] = useState<Record<string, string>>({});
  const [publisherKeys, setPublisherKeys] = useState<Record<string, string>>({});
  const [detail, setDetail] = useState<Comic | null>(null);
  const [progress, setProgress] = useState<Comic | null>(null);
  const [favoriteError, setFavoriteError] = useState("");
  useEffect(() => setActiveSaga(0), [seriesId]);
  useEffect(() => {
    const requestedId = new URLSearchParams(window.location.search).get("series");
    const requested = seriesList.find((item) => item.id === requestedId);
    if (requested) { setPublisher(requested.publisher); setSeriesId(requested.id); }
  }, [seriesList]);
  const publishers = useMemo(() => [...new Set(seriesList.map((series) => series.publisher))].sort((a, b) => a.localeCompare(b, "pt-BR")), [seriesList]);
  const groups = useMemo(() => seriesList.filter((series) => series.publisher === publisher && !series.parentSeriesId && (kind === "all" || (series.bannerTone === "saga" ? "saga" : "collection") === kind) && series.title.toLocaleLowerCase("pt-BR").includes(groupSearch.toLocaleLowerCase("pt-BR"))), [seriesList, publisher, kind, groupSearch]);
  const activeGroup = groups[Math.min(activeSeries, groups.length - 1)];
  const selectedSeries = seriesList.find((series) => series.id === seriesId);
  const parentSeries = selectedSeries?.parentSeriesId ? seriesList.find((series) => series.id === selectedSeries.parentSeriesId) : null;
  const childSagas = useMemo(() => seriesList.filter((series) => series.parentSeriesId === seriesId), [seriesList, seriesId]);
  const issues = useMemo(() => allComics.filter((comic) => comic.seriesId === seriesId).sort((a, b) => (a.volume || 0) - (b.volume || 0) || a.issueNumber - b.issueNumber || a.year - b.year), [allComics, seriesId]);
  const visibleIssues = useMemo(() => issues.filter((comic) => `${comic.title} ${comic.issueNumber} ${comic.characters.join(" ")}`.toLocaleLowerCase("pt-BR").includes(issueSearch.toLocaleLowerCase("pt-BR")) && (issueStatus === "all" || (comic.progress?.status || "not_started") === issueStatus)).sort((a,b) => issueSort === "recent" ? b.year - a.year || b.issueNumber - a.issueNumber : issueSort === "title" ? a.title.localeCompare(b.title, "pt-BR") : (a.volume || 0) - (b.volume || 0) || a.issueNumber - b.issueNumber), [issues, issueSearch, issueStatus, issueSort]);
  useEffect(() => { if (!supabase) return; let alive = true; void supabase.from("publisher_assets").select("publisher,logo_key").then(async ({ data }) => { const keys = Object.fromEntries((data || []).map((row) => [row.publisher, row.logo_key])); if (alive) setPublisherKeys(keys); }); return () => { alive = false; }; }, []);
  useEffect(() => { const keys = [...seriesList.map((item) => item.coverKey), ...Object.values(publisherKeys)].filter((key): key is string => !!key); if (keys.length) void getAssetUrls(keys).then(setAssetUrls); }, [seriesList, publisherKeys]);
  const publisherItems = publishers.map((name) => ({ id: name, title: name, subtitle: `${allComics.filter((comic) => comic.publisher === name).length} edições`, image: assetUrls[publisherKeys[name]] || publisherArt(name) || allComics.find((comic) => comic.publisher === name)?.coverUrl }));
  const issueCount = (id: string) => allComics.filter((comic) => comic.seriesId === id || seriesList.some((series) => series.id === comic.seriesId && series.parentSeriesId === id)).length;
  const seriesItems = groups.map((group) => ({ id: group.id, title: group.title, subtitle: `${favoriteSeriesIds.has(group.id) ? "♥ Favorita · " : ""}${issueCount(group.id)} edições · ${group.bannerTone === "saga" ? "Saga" : "Coleção"}`, image: assetUrls[group.coverKey || ""] || sagaArt(group.title) || allComics.find((comic) => comic.seriesId === group.id || seriesList.some((series) => series.id === comic.seriesId && series.parentSeriesId === group.id))?.coverUrl }));
  const sagaItems = childSagas.map((saga) => ({ id: saga.id, title: saga.title, subtitle: `${favoriteSeriesIds.has(saga.id) ? "♥ Favorita · " : ""}${issueCount(saga.id)} edições · ${saga.bannerTone === "one_shot" ? "Obra fechada" : saga.bannerTone === "phase" ? "Fase" : "Saga"}`, image: assetUrls[saga.coverKey || ""] || allComics.find((comic) => comic.seriesId === saga.id)?.coverUrl }));
  const favoriteButton = (series: typeof selectedSeries) => series && <button type="button" className={`collection-favorite-action ${favoriteSeriesIds.has(series.id) ? "active" : ""}`} aria-pressed={favoriteSeriesIds.has(series.id)} onClick={() => { setFavoriteError(""); void toggleSeriesFavorite(series.id).catch(() => setFavoriteError("Não foi possível salvar o favorito. Tente novamente.")); }}><Heart fill={favoriteSeriesIds.has(series.id) ? "currentColor" : "none"} />{favoriteSeriesIds.has(series.id) ? "Remover dos favoritos" : `Favoritar ${series.bannerTone === "saga" ? "saga" : series.bannerTone === "phase" ? "fase" : series.bannerTone === "one_shot" ? "obra" : "coleção"}`}</button>;
  const goPublishers = () => { setPublisher(null); setSeriesId(null); setActiveSeries(0); };
  return <div className="streaming-page series-page space-y-8">
    <header className="page-spotlight"><span className="page-kicker"><Layers /> Universos do acervo</span><h1>Coleções e sagas</h1><p>Escolha uma editora, encontre uma franquia ou saga e explore suas edições em ordem.</p></header>
    {favoriteError && <p role="alert" className="text-rose-400">{favoriteError}</p>}
    <nav aria-label="Caminho da coleção" className="flex flex-wrap items-center gap-2 text-xs text-slate-400"><button className="text-amber-300" onClick={goPublishers}>Editoras</button>{publisher && <><span>/</span><button className={seriesId ? "text-amber-300" : "text-white"} onClick={() => setSeriesId(null)}>{publisher}</button></>}{parentSeries && <><span>/</span><button className="text-amber-300" onClick={() => setSeriesId(parentSeries.id)}>{parentSeries.title}</button></>}{selectedSeries && <><span>/</span><span className="text-white">{selectedSeries.title}</span></>}</nav>
    {isLoading ? <div className="empty-collection-kind">Carregando coleções...</div> : selectedSeries ? <section className="collection-open" key={selectedSeries.id}>
      <button className="collection-back" onClick={() => setSeriesId(parentSeries?.id || null)}><ArrowLeft /> {parentSeries ? `Voltar a ${parentSeries.title}` : "Voltar às coleções"}</button><div className="collection-open-heading"><div><span>{selectedSeries.publisher} · {selectedSeries.startYear}</span><h2>{selectedSeries.title}</h2><p>{selectedSeries.description}</p>{favoriteButton(selectedSeries)}</div><strong>{issueCount(selectedSeries.id)} edições</strong></div>
      {childSagas.length > 0 && <section className="collection-hub" aria-label={`Fases, sagas e obras fechadas de ${selectedSeries.title}`}><CoverFlow items={sagaItems} activeIndex={activeSaga} onChange={setActiveSaga} onActivate={(item) => setSeriesId(item.id)} label={`Fases, sagas e obras fechadas de ${selectedSeries.title}`} /><div className="collection-hub-info"><div><span>Fases, sagas e obras fechadas</span><h3>{childSagas[Math.min(activeSaga, childSagas.length - 1)]?.title}</h3><small>{sagaItems[activeSaga]?.subtitle}</small></div><div className="collection-hub-actions">{favoriteButton(childSagas[Math.min(activeSaga, childSagas.length - 1)])}<button className="catalog-primary-action" onClick={() => setSeriesId(childSagas[Math.min(activeSaga, childSagas.length - 1)].id)}>Explorar título</button></div></div></section>}
      {issues.length > 0 && <h3>{childSagas.length ? "Edições da coleção" : "Edições"}</h3>}
      <div className="collection-filters"><label>Buscar edição<input value={issueSearch} onChange={(event) => setIssueSearch(event.target.value)} placeholder="Título, número ou personagem" /></label><label>Leitura<select value={issueStatus} onChange={(event) => setIssueStatus(event.target.value)}><option value="all">Todos os estados</option><option value="not_started">Não iniciadas</option><option value="reading">Em leitura</option><option value="completed">Concluídas</option></select></label><label>Ordenar<select value={issueSort} onChange={(event) => setIssueSort(event.target.value)}><option value="issue">Ordem da edição</option><option value="recent">Ano mais recente</option><option value="title">Título A–Z</option></select></label></div>
      {visibleIssues.length ? <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-3 sm:gap-4">{visibleIssues.map((comic) => <ComicCard key={comic.id} comic={comic} density="compact" onOpenReader={onOpenReader} onToggleFavorite={toggleFavorite} onOpenDetails={setDetail} onOpenProgressModal={setProgress} onMarkCompleted={(id, total) => setStatus(id, "completed", total)} onResetProgress={(id) => setStatus(id, "not_started", 10)} />)}</div> : !childSagas.length && <p className="empty-collection-kind">Nenhuma edição corresponde aos filtros.</p>}
    </section> : publisher ? <><div className="collection-kind-tabs" role="tablist" aria-label="Tipo de agrupamento">{(["all", "collection", "saga"] as const).map((option) => <button key={option} role="tab" aria-selected={kind === option} className={kind === option ? "active" : ""} onClick={() => { setKind(option); setActiveSeries(0); }}>{option === "all" ? "Todos" : option === "collection" ? "Coleções" : "Sagas"}<span>{seriesList.filter((series) => series.publisher === publisher && !series.parentSeriesId && (option === "all" || (series.bannerTone === "saga" ? "saga" : "collection") === option)).length}</span></button>)}</div><div className="collection-filters"><label>Filtrar coleções e sagas<input value={groupSearch} onChange={(event) => { setGroupSearch(event.target.value); setActiveSeries(0); }} placeholder="Nome da coleção ou saga" /></label></div>{groups.length ? <section className="collection-hub" aria-label={`Franquias de ${publisher}`}><CoverFlow items={seriesItems} activeIndex={activeSeries} onChange={setActiveSeries} onActivate={(item) => setSeriesId(item.id)} label={`Coleções de ${publisher}`} />{activeGroup && <div className="collection-hub-info"><div><span>{publisher} · {activeGroup.startYear}</span><h2>{activeGroup.title}</h2><p>{activeGroup.description || "Explore as edições desta coleção."}</p><small>{seriesItems[activeSeries]?.subtitle}</small></div><div className="collection-hub-actions">{favoriteButton(activeGroup)}<button className="catalog-primary-action" onClick={() => setSeriesId(activeGroup.id)}>Explorar edições</button></div></div>}</section> : <div className="empty-collection-kind">Nenhuma coleção deste tipo encontrada.</div>}</> : publishers.length ? <section className="collection-hub publisher-flow" aria-label="Editoras e selos"><CoverFlow items={publisherItems} activeIndex={activePublisher} onChange={setActivePublisher} onActivate={(item) => setPublisher(item.id)} label="Editoras do acervo" /><div className="collection-hub-info"><div><span>Editora ou selo</span><h2>{publishers[activePublisher]}</h2><p>{publisherItems[activePublisher]?.subtitle} no acervo</p></div><button className="catalog-primary-action" onClick={() => setPublisher(publishers[activePublisher])}>Explorar coleções</button></div></section> : <div className="empty-collection-kind">Nenhuma coleção cadastrada.</div>}
    <ComicDetailModal comic={detail} isOpen={!!detail} onClose={() => setDetail(null)} onOpenReader={onOpenReader} onToggleFavorite={toggleFavorite} onOpenProgressModal={setProgress} onMarkCompleted={(id, total) => setStatus(id, "completed", total)} onResetProgress={(id) => setStatus(id, "not_started", 10)} />
    <ProgressUpdateModal comic={progress} isOpen={!!progress} onClose={() => setProgress(null)} onSaveProgress={updateProgress} />
  </div>;
};
